/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ingest-alert': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'incident.detected'; data: never }>
    'notify-human': EventHandler<never, never>
    'approve-fix': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'approval.received'; data: never }>
    'execute-fix': EventHandler<never, never>
    'analyze-incident': EventHandler<never, { topic: 'human.approval.needed'; data: never }>
  }
    
}