/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'log-resolution': EventHandler<never, never>
    'create-ticket': EventHandler<never, never>
    'hourly-health-check': CronHandler<{ topic: 'incident.detected'; data: never }>
    'execute-fix': EventHandler<never, { topic: 'incident.resolved'; data: never }>
    'notify-human': EventHandler<never, never>
    'analyze-incident': EventHandler<never, { topic: 'human.approval.needed'; data: never }>
    'ingest-alert': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'incident.detected'; data: never }>
    'approve-fix': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'approval.received'; data: never } | { topic: 'ticket.escalation'; data: never }>
  }
    
}